USE [master]
GO

/****** Object:  Database [PlatoonMedic]    Script Date: 3/23/2023 6:55:30 PM ******/
CREATE DATABASE [PlatoonMedic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PlatoonMedic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PlatoonMedic.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'PlatoonMedic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PlatoonMedic_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PlatoonMedic].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PlatoonMedic] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PlatoonMedic] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PlatoonMedic] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PlatoonMedic] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PlatoonMedic] SET ARITHABORT OFF 
GO

ALTER DATABASE [PlatoonMedic] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [PlatoonMedic] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PlatoonMedic] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PlatoonMedic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PlatoonMedic] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PlatoonMedic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PlatoonMedic] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PlatoonMedic] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PlatoonMedic] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PlatoonMedic] SET  ENABLE_BROKER 
GO

ALTER DATABASE [PlatoonMedic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PlatoonMedic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PlatoonMedic] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PlatoonMedic] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PlatoonMedic] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PlatoonMedic] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PlatoonMedic] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PlatoonMedic] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PlatoonMedic] SET  MULTI_USER 
GO

ALTER DATABASE [PlatoonMedic] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PlatoonMedic] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PlatoonMedic] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PlatoonMedic] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [PlatoonMedic] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PlatoonMedic] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [PlatoonMedic] SET QUERY_STORE = OFF
GO

ALTER DATABASE [PlatoonMedic] SET  READ_WRITE 
GO


